### ISSUE TITLE
Homework #4

### ISSUE THREAD

**Issue by Benjamin-Douglas** [Benjamin-Douglas/Astr_119_Homework#1]
Please grade my homework @adwasser

import numpy as np

import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi, 1000)
a = 5*np.cos(2*x) + 5.5
b = .02*np.exp(x)
c = .25*x**2 + .1*np.sin(10*x)
plt.plot(x,a)
plt.xlabel('Time in ASTR / EART 119')
plt.ylabel('Measures of Awesomeness')
plt.plot(x,b)
plt.plot(x,c)
plt.show()

**Comment by Benjamin-Douglas** [comment]
I'm not able to upload a .py file nor a .ipynp file, why not/how would I be able to do that for you.

**Comment by adwasser** [comment]
@Benjamin-Douglas , you should be able to upload files from the main page of the repository in the upper right, near the green button for clone/download.  If you're still having issues please find me before or after class.
